; FlowField/Config/DefaultEngine.ini

[/Script/Engine.CollisionProfile]
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel1,DefaultResponse=ECR_Ignore,bTraceType=True,bStaticObject=False,Name="FlowFieldChannel")
+EditProfiles=(Name="BlockAll",CustomRe我sponses=((Channel="FlowFieldChannel",Response=ECR_Ignore)))