[CoreRedirects]
;+ClassRedirects=(OldName="/Script/FlowField.MassFlowFieldTransformToActorTranslator",NewName="/Script/FlowField.FlowFieldTransformToActorTranslator")
;+StructRedirects=(OldName="/Script/FlowField.FlowFieldBoidsFragment",NewName="/Script/FlowField.FlowFieldBoidsProcessor")
;+StructRedirects=(OldName="/Script/FlowField.FlowFieldAgentNetData",NewName="/Script/FlowField.FlowFieldAgentReplicator")
;+ClassRedirects=(OldName="/Script/FlowField.MonsterSpatialHashProcessor",NewName="/Script/FlowField.FlowFieldSpatialHashProcessor")